on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build-website

jobs:
  build-website:
    runs-on: ubuntu-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_AUTOLOADER_ENABLED: false

    steps:
      - uses: actions/checkout@v3

      - id: setup
        uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install torch
        run: Rscript -e "torch::install_torch()"

      - name: Render site
        run: quarto render .
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'deploy website'
          branch: gh-pages
          folder: _site
          single-commit: true
